CREATE TABLE IF NOT EXISTS ehr.OphthalmologyDiagnosesDm (
    DX_ID INTEGER,
    DX_NAME VARCHAR(500),
    LINE INTEGER,
    CODE VARCHAR(100),
    CODE_TYPE VARCHAR(100),
    DX_GROUP VARCHAR(100),
    DX_GROUP_ID INTEGER

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologyProviderAll (
    PROV_ID VARCHAR(100),
    PROV_NAME VARCHAR(100),
    PROV_TYPE VARCHAR(100),
    UPIN VARCHAR(100),
    ACTIVE_STATUS VARCHAR(100),
    CLINICIAN_TITLE VARCHAR(100),
    SEX VARCHAR(100),
    REFERRAL_SOURCE_TYPE VARCHAR(100),
    RECORD_TYPE INTEGER,
    DOCTORS_DEGREE VARCHAR(100),
    USER_ID VARCHAR(100),
    OPH_YN VARCHAR(100),
    UM_NUM VARCHAR(100),
    LICENSE VARCHAR(100),
    NPI VARCHAR(100),
    SPECIALTY VARCHAR(100),
    SYSTEM_LOGIN VARCHAR(100),
    DEPARTMENT_NAME VARCHAR(100),
    LOC_NAME VARCHAR(100),
    CENTER VARCHAR(100),
    DEF_DIVISION VARCHAR(100),
    FIRST_ENC_DATE TIMESTAMP WITH TIME ZONE,
    LAST_ENC_DATE TIMESTAMP WITH TIME ZONE,
    TOTAL_ENC INTEGER

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologyRadiology (
    PAT_MRN VARCHAR(100),
    ACESSION_NUM BIGINT,
    MODALITY VARCHAR(100),
    BEGIN_EXAM_DTTM TIMESTAMP WITH TIME ZONE,
    END_EXAM_DTTM TIMESTAMP WITH TIME ZONE,
    FINALIZING_DTTM TIMESTAMP WITH TIME ZONE,
    PERFORM_PROC_CODE VARCHAR(100),
    PERFORM_PROC_NAME VARCHAR(100),
    AUTHORIZING_PROV_NAME VARCHAR(100),
    ORDERING_PROV_NAME VARCHAR(100),
    APPT_NOTE VARCHAR(100),
    ORDERING_DEP VARCHAR(100),
    ORDERING_PROV_ID VARCHAR(100),
    AUTHORIZING_PROV_ID VARCHAR(100),
    TEXT VARCHAR(100)

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologyFamilyHistory (
    PAT_MRN VARCHAR(100),
    PAT_ID VARCHAR(100),
    RECENT_PAT_ENC_CSN_ID INTEGER,
    RECENT_CONTACT_DATE TIMESTAMP WITH TIME ZONE,
    MEDICAL_HX VARCHAR(100),
    RELATION VARCHAR(100),
    HISTORY_SOURCE VARCHAR(100),
    COMMENTS VARCHAR(100),
    FAM_STAT_NAME VARCHAR(100),
    FAM_STATUS VARCHAR(100),
    AGE_OF_ONSET INTEGER,
    FAM_STAT_ID INTEGER

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologyPatientDiagnoses (
    PAT_MRN VARCHAR(100),
    PAT_ID VARCHAR(100),
    DX_ID INTEGER,
    DX_SOURCE_ID INTEGER,
    DX_SOURCE_DATE TIMESTAMP WITH TIME ZONE,
    DX_SOURCE VARCHAR(100),
    LINE INTEGER

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologyImplant (
    PAT_MRN VARCHAR(100),
    PAT_ID VARCHAR(100),
    LOG_ID VARCHAR(100),
    CASE_ID VARCHAR(100),
    OR_PROC_NAME VARCHAR(500),
    IMPLANT_NAME VARCHAR(100),
    IMPLANT_TYPE VARCHAR(100),
    LATERALITY VARCHAR(100),
    IMPLANT_AREA VARCHAR(100),
    OR_PROC_ID VARCHAR(100),
    IMPLANT_ID INTEGER

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologyCurrentMedications (
    PAT_MRN VARCHAR(100),
    PAT_ID VARCHAR(100),
    PAT_ENC_CSN_ID INTEGER,
    MEDICATION_ID INTEGER,
    ORDER_MED_ID INTEGER,
    LINE INTEGER,
    NAME VARCHAR(500),
    GENERIC VARCHAR(100),
    THERAPEUTIC_CLASS VARCHAR(100),
    PHARMACEUTICAL_CLASS VARCHAR(100),
    STRENGTH VARCHAR(100),
    ORDERING_DTTM TIMESTAMP WITH TIME ZONE,
    UPDATE_DTTM TIMESTAMP WITH TIME ZONE,
    ADD_TO_LIST_TM TIMESTAMP WITH TIME ZONE,
    FREQUENCY VARCHAR(100),
    CONTACT_DATE TIMESTAMP WITH TIME ZONE

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologySupplyDm (
    OR_SUPPLY_CAT INTEGER,
    LINE INTEGER,
    SUPPLY_ID VARCHAR(100),
    SZ INTEGER,
    SUPPLY_NAME VARCHAR(500)

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologyImplantDm (
    IMPLANT_ID VARCHAR(100),
    IMPLANT_NAME VARCHAR(100),
    IMPLANT_TYPE VARCHAR(100),
    MANUFACTURER VARCHAR(100)

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologySurgeryProcedure (
    CASE_ID VARCHAR(100),
    LOG_ID VARCHAR(100),
    PAT_MRN VARCHAR(100),
    PAT_ID VARCHAR(100),
    LINE INTEGER,
    OR_ANESTH_TYPE VARCHAR(100),
    OR_LATERALITY VARCHAR(100),
    ALL_PROC_PANEL INTEGER,
    COMMENTS VARCHAR(100),
    PROC_DISPLAY_NAME VARCHAR(500),
    OR_PROC_ID VARCHAR(100)

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.C3304_2_CORIS_to_SOURCE (
    SOURCEid VARCHAR(100),
    CORISid BIGINT

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologyEncounterCharge (
    UCL_ID VARCHAR(100),
    PAT_ENC_CSN_ID INTEGER,
    PAT_ID VARCHAR(100),
    PAT_MRN VARCHAR(100),
    PROC_CODE VARCHAR(100),
    PROC_DESCRIPTION VARCHAR(100),
    SERVICE_DATE_DT TIMESTAMP WITH TIME ZONE,
    SERVICE_PROVIDER VARCHAR(100),
    MODIFIER VARCHAR(500),
    QUANTITY NUMERIC(18,6),
    BILL_AREA VARCHAR(100),
    COST_CENTER_NAME VARCHAR(100),
    PROCEDURE_ID INTEGER,
    SERVICE_PROVIDER_ID VARCHAR(100),
    BILLING_PROVIDER_ID VARCHAR(100),
    HOSPITAL_ACCOUNT_ID INTEGER,
    TransactionSubtype VARCHAR(100)

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologySurgeryMedication (
    LOG_ID VARCHAR(100),
    CASE_ID VARCHAR(100),
    PAT_MRN VARCHAR(100),
    PAT_IN_OR_DATETIME TIMESTAMP WITH TIME ZONE,
    PAT_ID VARCHAR(100),
    ORDER_MED_ID INTEGER,
    MAR_ENC_CSN INTEGER,
    MED_CAT VARCHAR(100),
    MED_SUBCAT VARCHAR(100),
    ADMIN_DOSE VARCHAR(100),
    UNIT VARCHAR(100),
    ROUTE VARCHAR(100),
    THERAPEUTIC_CLASS VARCHAR(100),
    PHARMACEUTICAL_CALSS VARCHAR(100),
    ORDER_PLACE_DATETIME TIMESTAMP WITH TIME ZONE,
    ORDER_START_TIME TIMESTAMP WITH TIME ZONE,
    ORDER_END_TIME TIMESTAMP WITH TIME ZONE,
    DISCONTINUE_DATTIME TIMESTAMP WITH TIME ZONE,
    TAKEN_TIME TIMESTAMP WITH TIME ZONE,
    ORDERING_MODE VARCHAR(100),
    MEDICATION_ID INTEGER,
    NAME VARCHAR(100),
    LINE INTEGER,
    GENERIC_NAME VARCHAR(100),
    ORDER_STATUS VARCHAR(100),
    ADMIN_ACTION VARCHAR(100),
    MED_PRESC_PROV_NAME VARCHAR(100),
    MED_PRESC_PROV_ID VARCHAR(100)

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologySurgerySurgeon (
    CASE_ID VARCHAR(100),
    LOG_ID VARCHAR(100),
    PAT_MRN VARCHAR(100),
    PAT_ID VARCHAR(100),
    LINE INTEGER,
    SURGEON_NAME VARCHAR(100),
    ROLE VARCHAR(100),
    OR_SERVICE VARCHAR(100),
    START_TIME TIMESTAMP WITH TIME ZONE,
    END_TIME TIMESTAMP WITH TIME ZONE,
    TOTAL_LENGTH INTEGER,
    PANEL INTEGER,
    SURG_ID VARCHAR(100),
    ROLE_C INTEGER,
    SERVICE_C VARCHAR(100)

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologyEncounterExam (
    CONCEPT_ID VARCHAR(100),
    CONCEPT_NAME VARCHAR(500),
    PAT_MRN VARCHAR(100),
    PAT_ID VARCHAR(100),
    PAT_ENC_CSN_ID INTEGER,
    CUR_VALUE_DATETIME TIMESTAMP WITH TIME ZONE,
    ELEMENT_VALUE_ID INTEGER,
    LINE INTEGER,
    SMRTDTA_ELEM_VALUE VARCHAR(500),
    CONTACT_DATE TIMESTAMP WITH TIME ZONE

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologyEncounters (
    PAT_ENC_CSN_ID INTEGER,
    PAT_ID VARCHAR(100),
    PAT_MRN VARCHAR(100),
    HSP_ACCOUNT_ID INTEGER,
    PAT_AGE_AT_ENC INTEGER,
    PAT_CLASS VARCHAR(100),
    ENC_TYPE VARCHAR(100),
    DEPARTMENT_NAME VARCHAR(100),
    PRIMARY_LOCATION VARCHAR(100),
    LOS_PRIME_PROC_CODE VARCHAR(100),
    LOS_PRIME_PROC_NAME VARCHAR(100),
    LOS_PRIME_CAT VARCHAR(100),
    VISIT_PROVIDER VARCHAR(100),
    PCP_PROVIDER VARCHAR(100),
    REFERRAL_NAME VARCHAR(100),
    SPECIALTY VARCHAR(100),
    ADMISSION_TYPE VARCHAR(100),
    VISIT_TYPE VARCHAR(100),
    APPT_STATUS VARCHAR(100),
    REASON_FOR_VISIT VARCHAR(500),
    OBGYN_Status VARCHAR(100),
    TOBACCO_USE VARCHAR(100),
    ALCOHOL_USE VARCHAR(100),
    ILL_DRUG_USE VARCHAR(100),
    TOBACCO_USED_YEARS VARCHAR(100),
    SMOKING_START_DATE TIMESTAMP WITH TIME ZONE,
    SMOKING_QUIT_DATE TIMESTAMP WITH TIME ZONE,
    ENTRY_TIME TIMESTAMP WITH TIME ZONE,
    APPT_MADE_DATE TIMESTAMP WITH TIME ZONE,
    CONTACT_DATE TIMESTAMP WITH TIME ZONE,
    APPT_TIME TIMESTAMP WITH TIME ZONE,
    BEGIN_CHECKIN_DTTM TIMESTAMP WITH TIME ZONE,
    CHECKIN_TIME TIMESTAMP WITH TIME ZONE,
    CHECKOUT_TIME TIMESTAMP WITH TIME ZONE,
    ENC_CLOSE_TIME TIMESTAMP WITH TIME ZONE,
    UPDATE_DATE TIMESTAMP WITH TIME ZONE,
    EFFECTIVE_DATE_DTTM TIMESTAMP WITH TIME ZONE,
    PAT_VIS_WAIT INTEGER,
    PAT_VIS_TM_W_NURSE INTEGER,
    PAT_TM_W_FOR_PHYS INTEGER,
    PAT_VIS_TM_W_PHYS INTEGER,
    APPT_LENGTH INTEGER,
    BP_SYSTOLIC INTEGER,
    BP_DIASTOLIC INTEGER,
    TEMPERATURE NUMERIC(18,6),
    PULSE INTEGER,
    WEIGHT NUMERIC(18,6),
    HEIGHT VARCHAR(100),
    BMI NUMERIC(18,6),
    BSA NUMERIC(18,6),
    ENC_CLOSED_YN VARCHAR(100),
    REFERRAL_REQ_YN VARCHAR(100),
    NONCVRED_SERVICE_YN VARCHAR(100),
    PRE_VIS_CHART_AMT INTEGER,
    POST_VIS_CHART_AMT INTEGER,
    SEQUENTIAL_APPT_YN VARCHAR(100),
    DX_UNIQUE_COUNTER VARCHAR(100),
    CNCT_ARCHIVED_YN VARCHAR(100),
    APPT_RESCH_YN VARCHAR(100),
    APPT_SERIAL_NO INTEGER,
    INPATIENT_DATA_ID VARCHAR(100),
    CHARGE_SLIP_NUMBER VARCHAR(100),
    PAT_CLASS_C INTEGER,
    hx_pat_enc_csn_id INTEGER,
    ENC_CLOSED_USER_ID VARCHAR(100),
    LOS_PRIME_PROC_ID INTEGER,
    PCP_PROV_ID VARCHAR(100),
    VISIT_PROV_ID VARCHAR(100),
    DEPARTMENT_ID INTEGER,
    APPT_PRC_ID VARCHAR(100),
    APPT_ENTRY_USER_ID VARCHAR(100),
    CHECKIN_USER_ID VARCHAR(100),
    REFERRAL_ID INTEGER,
    ACCOUNT_ID INTEGER,
    COVERAGE_ID INTEGER,
    PRIMARY_LOC_ID INTEGER,
    VISIT_EPM_ID VARCHAR(100),
    VISIT_EPP_ID BIGINT,
    SERV_AREA_ID INTEGER,
    IP_EPISODE_ID INTEGER,
    REFERRAL_SOURCE_ID VARCHAR(100),
    ENC_BILL_AREA_ID INTEGER,
    CHKOUT_USER_ID VARCHAR(100)

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologyVisitSummary (
    PAT_ENC_CSN_ID INTEGER,
    PAT_MRN VARCHAR(100),
    PAT_ID VARCHAR(100),
    TITLE VARCHAR(100),
    FOLLOWUP_NUMBER INTEGER,
    FOLLOWUP_UNIT VARCHAR(100),
    FOLLOWUP_INFO VARCHAR(100),
    PRN_TEXT VARCHAR(100),
    HPI VARCHAR(100),
    TECH_COMMENT VARCHAR(100),
    PAT_OCULAR_HISTORY VARCHAR(100)

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologySurgery (
    PAT_MRN VARCHAR(100),
    PAT_ID VARCHAR(100),
    SURGERY_CSN_ID INTEGER,
    PAT_ENC_CSN_ID INTEGER,
    CASE_ID VARCHAR(100),
    LOG_ID VARCHAR(100),
    OR_CASE_TYPE VARCHAR(100),
    OR_CASE_CLASS VARCHAR(100),
    PROC_LEVEL VARCHAR(100),
    NUM_OF_PANELS INTEGER,
    PRE_OP_DIAG VARCHAR(100),
    OR_POSTOP_DEST VARCHAR(100),
    HSP_ACCOUNT_ID INTEGER,
    PATIENT_CLASS VARCHAR(100),
    PATIENT_TYPE_CD VARCHAR(100),
    OR_SERVICE VARCHAR(100),
    LOCATION VARCHAR(100),
    ROOM VARCHAR(100),
    OR_STATUS VARCHAR(100),
    OR_ANESTH_TYPE VARCHAR(100),
    OR_LATERALITY VARCHAR(100),
    SITE VARCHAR(100),
    INCISION_CLOSURE VARCHAR(100),
    OR_WOUND_CLASS VARCHAR(100),
    PRIMARY_PHYSICAN VARCHAR(100),
    ANESTHESIOLOGIST VARCHAR(100),
    PNL_ VARCHAR(500),
    ALL_PROC_AS_ORDERED VARCHAR(500),
    TOTAL_TIME_NEEDED INTEGER,
    SCHED_START_TIME TIMESTAMP WITH TIME ZONE,
    PREOP_PRESENT_DATETIME TIMESTAMP WITH TIME ZONE,
    RN_ASSESS_COMPLETE_DATETIME TIMESTAMP WITH TIME ZONE,
    ROOM_READY_DATETIME TIMESTAMP WITH TIME ZONE,
    PAT_IN_OR_DATETIME TIMESTAMP WITH TIME ZONE,
    INCISION_START_DATETIME TIMESTAMP WITH TIME ZONE,
    DRESSING_END_DATETIME TIMESTAMP WITH TIME ZONE,
    OUT_OR_DATETIME TIMESTAMP WITH TIME ZONE,
    COMPLETE_DATETIME TIMESTAMP WITH TIME ZONE,
    INPATIENT_DATA_ID VARCHAR(100),
    SERVICE_C VARCHAR(100),
    PNL_1_PRIM_PROC_EXT_ID VARCHAR(100),
    PNL_1_PRIM_SURG_PROC_ID VARCHAR(100),
    PRIMARY_PHYS_ID VARCHAR(100),
    ANES_prov_id VARCHAR(100),
    CPT1 VARCHAR(100),
    CPT2 VARCHAR(100),
    CPT3 VARCHAR(100),
    CPT4 VARCHAR(100),
    CPT5 VARCHAR(100),
    MOD1 VARCHAR(500),
    MOD2 VARCHAR(500),
    MOD3 VARCHAR(500),
    MOD4 VARCHAR(500),
    MOD5 VARCHAR(500),
    ARGUSIMPLANT VARCHAR(100),
    BCL VARCHAR(100),
    CONFORMER VARCHAR(100),
    CORNEAL_PUNCH VARCHAR(100),
    DIATHERMY_PROBE VARCHAR(100),
    FRAGMATOME VARCHAR(100),
    GAS VARCHAR(100),
    IOL VARCHAR(100),
    IRIS_HOOK VARCHAR(100),
    I_TRACK VARCHAR(100),
    KAHOOK_DUAL VARCHAR(100),
    LASER_PROBE VARCHAR(100),
    MAL_RING VARCHAR(100),
    PERFLUORON VARCHAR(100),
    SEALANT_EVICEL VARCHAR(100),
    SEALANT_RESURE VARCHAR(100),
    SIL_OIL VARCHAR(100),
    SUTURE_CG VARCHAR(100),
    SUTURE_ETHILON VARCHAR(100),
    SUTURE_GT VARCHAR(100),
    SUTURE_MERSILENE VARCHAR(100),
    SUTURE_MONOCRYL VARCHAR(100),
    SUTURE_NYLON VARCHAR(100),
    SUTURE_PDS VARCHAR(100),
    SUTURE_PG VARCHAR(100),
    SUTURE_PP VARCHAR(100),
    SUTURE_PROLENE VARCHAR(100),
    SUTURE_SILK VARCHAR(100),
    SUTURE_VICRYL VARCHAR(100),
    TKP VARCHAR(100),
    VISCO_360 VARCHAR(100),
    VISC_DUOVISC VARCHAR(100),
    VISC_HEALON VARCHAR(100),
    VISC_OCUCOAT VARCHAR(100),
    VISC_PROVISC VARCHAR(100),
    VISC_VISCOAT VARCHAR(100),
    VITRECTOMY_PACK VARCHAR(100),
    VIT_ACCURUS VARCHAR(100),
    VIT_CONSTELLATION VARCHAR(100),
    VIT_INFINITY VARCHAR(100),
    VIT_OCCUTOME VARCHAR(100),
    VIT_OTHER VARCHAR(100),
    CT_TISSUE_FOR_SURGERY VARCHAR(100),
    CT_KPRO VARCHAR(100),
    GDD_TYPE VARCHAR(100),
    GDD_MIGS VARCHAR(100),
    GDD_PATCH_GRAFT VARCHAR(100),
    GDD_OTHER VARCHAR(100),
    CAT_ANTERIOR_POSTERIOR VARCHAR(100),
    CAT_TYPE VARCHAR(100),
    CAT_COMPANY VARCHAR(100),
    CAT_MODEL VARCHAR(100),
    CAT_POWER VARCHAR(100),
    CAT_CTR VARCHAR(100),
    RET_SB VARCHAR(100),
    RET_ARGUS VARCHAR(100),
    RET_RETISERT VARCHAR(100),
    OP_NOTE VARCHAR(100),
    BRIEF_OP_NOTE VARCHAR(100)

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.C3304_T11_Notes (
    Arb_Person_Id BIGINT,
    Arb_Encounter_Id BIGINT,
    NoteEpicId BIGINT,
    NoteType VARCHAR(100),
    NoteText TEXT,
    NoteProvider VARCHAR(100),
    DateOfNote TIMESTAMP WITH TIME ZONE,
    TimeOfNote TIME

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologyMedicationDm (
    MED_CAT VARCHAR(100),
    MED_SUBCAT VARCHAR(100),
    THERAPEUTIC_CLASS VARCHAR(100),
    PHARMACEUTICAL_CLASS VARCHAR(100),
    MEDICATION_ID INTEGER,
    NAME VARCHAR(100),
    GENERIC_NAME VARCHAR(100)

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologyLabOrder (
    PAT_MRN VARCHAR(100),
    PAT_ID VARCHAR(100),
    PAT_ENC_CSN_ID INTEGER,
    ORDER_ID INTEGER,
    ACCESSION_NUM BIGINT,
    PROC_CODE VARCHAR(100),
    DISPLAY_NAME VARCHAR(100),
    EXTERNAL_ORD_ID VARCHAR(100),
    ABNORMAL_YN VARCHAR(100),
    ORDERING_DATE TIMESTAMP WITH TIME ZONE,
    SPECIMEN_TYPE VARCHAR(100),
    SPECIMEN_TAKEN_TIME TIMESTAMP WITH TIME ZONE,
    SPECIMEN_RECV_TIME TIMESTAMP WITH TIME ZONE,
    SPECIMEN_COMMENTS VARCHAR(100),
    ORDER_TYPE VARCHAR(100),
    ORDER_STATUS VARCHAR(100),
    LAB_STATUS VARCHAR(100),
    ORDER_CLASS VARCHAR(100),
    ORDER_PRIORITY VARCHAR(100),
    ORDERING_PROV_NAME VARCHAR(100),
    AUTHRZING_PROV_NAME VARCHAR(100),
    ORDERING_PROV_ID VARCHAR(100),
    AUTHRZING_PROV_ID VARCHAR(100),
    LAB_STATUS_C INTEGER

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologyMedications (
    ORDER_MED_ID INTEGER,
    PAT_MRN VARCHAR(100),
    PAT_ID VARCHAR(100),
    PAT_ENC_CSN_ID INTEGER,
    ORDER_STATUS VARCHAR(100),
    MED_PRESC_PROV_NAME VARCHAR(100),
    ORDERING_DTTM TIMESTAMP WITH TIME ZONE,
    ORDER_START_DATE TIMESTAMP WITH TIME ZONE,
    ORDER_END_DATE TIMESTAMP WITH TIME ZONE,
    DISCONTINUE_DATETIME TIMESTAMP WITH TIME ZONE,
    NAME VARCHAR(500),
    GENERIC VARCHAR(100),
    THERAPEUTIC_CLASS VARCHAR(100),
    PHARMACEUTICAL_CLASS VARCHAR(100),
    STRENGTH VARCHAR(100),
    MED_DOSE_UNIT VARCHAR(100),
    ADMIN_DOSE_UNIT VARCHAR(100),
    MED_ROUTE VARCHAR(100),
    HV_DISCRETE_DOSE VARCHAR(100),
    QUANTITY VARCHAR(100),
    MED_DIS_DISP_QTY NUMERIC(18,6),
    TOTAL_DOSES INTEGER,
    TOTAL_REMAINING_DOSES INTEGER,
    REFILLS VARCHAR(100),
    INSTRUCTION INTEGER,
    FREQUENCY VARCHAR(100),
    PAT_ENC_DATE_REAL NUMERIC(18,6),
    MEDICATION_ID INTEGER,
    MED_PRESC_PROV_ID VARCHAR(100),
    GPI VARCHAR(100),
    MED_ROUTE_C VARCHAR(100),
    HV_DOSE_UNIT_C INTEGER,
    MAX_DOSE_UNIT_C INTEGER,
    ORDER_STATUS_C INTEGER,
    HV_DISCR_FREQ_ID VARCHAR(100),
    PHARMACY_ID INTEGER,
    DISP_AS_WRITTEN_YN VARCHAR(100),
    RSN_FOR_DISCON VARCHAR(100),
    EXT_FORMULARY_ID VARCHAR(100),
    EXT_COVERAGE_ID VARCHAR(100),
    EXT_COPAY_ID VARCHAR(100),
    EXT_PHARMACY_TYPE VARCHAR(100),
    EXT_FORMULARY_STAT VARCHAR(100),
    COST VARCHAR(100)

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologySurgeryBill (
    LOG_ID VARCHAR(100),
    UCL_ID VARCHAR(100),
    YearServiceDate VARCHAR(100),
    QUANTITY NUMERIC(18,6),
    PROCEDURE_ID INTEGER,
    SERVICE_PROVIDER_ID VARCHAR(100),
    BILLING_PROVIDER_ID VARCHAR(100),
    CPT_CODE VARCHAR(100),
    PROC_DESCRIPTION VARCHAR(100),
    COST_CENTER_NAME VARCHAR(100),
    BILL_AREA VARCHAR(100),
    SPECIALTY VARCHAR(100),
    LOC_NAME VARCHAR(100),
    HOSPITAL_ACCOUNT_ID INTEGER,
    MODIFIERS VARCHAR(500),
    CODE_TYPE_C INTEGER

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologySupply (
    PAT_MRN VARCHAR(100),
    PAT_ID VARCHAR(100),
    LOG_ID VARCHAR(100),
    CASE_ID VARCHAR(100),
    OR_PROC_NAME VARCHAR(500),
    OR_PROC_ID VARCHAR(100),
    OR_SUPPLY_CAT VARCHAR(100),
    SZ VARCHAR(100),
    SUPPLY_ID VARCHAR(100),
    SUPPLY_NAME VARCHAR(500),
    quantity INTEGER

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologyProviderDm (
    PROV_ID VARCHAR(100),
    PROV_NAME VARCHAR(100),
    DEPARTMENT_ID TEXT,
    DEPARTMENT_NAME VARCHAR(100),
    DEPT_ABBREVIATION VARCHAR(100)

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologyEncounterProblemList (
    PROBLEM_LIST_ID INTEGER,
    PAT_ENC_CSN_ID INTEGER,
    PAT_MRN VARCHAR(100),
    PAT_ID VARCHAR(100),
    DX_ID INTEGER,
    DX_NAME VARCHAR(500),
    NOTED_DATE TIMESTAMP WITH TIME ZONE,
    RESOLVED_DATE TIMESTAMP WITH TIME ZONE,
    DATE_OF_ENTRY TIMESTAMP WITH TIME ZONE,
    PROBLEM_CMT VARCHAR(100),
    PRINCIPAL_PL_YN VARCHAR(100)

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologyLabs (
    PAT_MRN VARCHAR(100),
    PAT_ID VARCHAR(100),
    ORDER_ID INTEGER,
    COMPONENT_ID INTEGER,
    RESULT_DATE TIMESTAMP WITH TIME ZONE,
    RESULT_LINE INTEGER,
    COMPONENT_NAME VARCHAR(100),
    ORD_VALUE NUMERIC(18,6),
    RESULT_FLAG VARCHAR(100),
    REF_NORMAL_VALS VARCHAR(500),
    REFERENCE_LOW VARCHAR(500),
    REFERENCE_HIGH VARCHAR(500),
    REFERENCE_UNIT VARCHAR(100),
    LINE_COMMENT TEXT,
    RESULT_FLAG_C INTEGER,
    RESULTS_COMP_CMT TEXT,
    RESULTS_CMT TEXT

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologyPatients (
    PAT_ID VARCHAR(100),
    PAT_MRN VARCHAR(100),
    PAT_SEX VARCHAR(100),
    BIRTH_DATE TIMESTAMP WITH TIME ZONE,
    ETHNIC VARCHAR(100),
    RACE VARCHAR(100),
    MARITAL VARCHAR(100),
    RELIGION VARCHAR(100),
    LANGUAGE VARCHAR(100),
    LIVING_STATUS VARCHAR(100),
    ADDRESS_LINE VARCHAR(500),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    COUNTY VARCHAR(100),
    COUNTRY VARCHAR(100),
    ZIP VARCHAR(100),
    REG_STATUS VARCHAR(100),
    CUR_PCP_PROV_NAME VARCHAR(100),
    CUR_PRIM_LOC_NAME VARCHAR(100),
    EMPLOY_STATUS VARCHAR(100),
    comp_appts_count INTEGER,
    noshow_appts_count INTEGER,
    NO_SHOW_RATE NUMERIC(18,6),
    PRIM_FINANCIAL_CLASS VARCHAR(100),
    FIRST_APPT_DEPARTMENT VARCHAR(100),
    TOBACCO_USE VARCHAR(100),
    ALCOHOL_USE VARCHAR(100),
    ILL_DRUG_USE VARCHAR(100),
    SMOKING_START_DATE TIMESTAMP WITH TIME ZONE,
    SMOKING_END_DATE TIMESTAMP WITH TIME ZONE,
    TOBACCO_USED_YEARS VARCHAR(100),
    REG_DATE TIMESTAMP WITH TIME ZONE,
    REC_CREATE_DATE TIMESTAMP WITH TIME ZONE,
    DEATH_DATE TIMESTAMP WITH TIME ZONE,
    ALRGY_UPD_DATE TIMESTAMP WITH TIME ZONE,
    MEDS_LAST_REV_TM TIMESTAMP WITH TIME ZONE,
    UPDATE_DATE TIMESTAMP WITH TIME ZONE,
    EPT_LOG_DATE TIMESTAMP WITH TIME ZONE,
    ALRGY_UPD_INST TIMESTAMP WITH TIME ZONE,
    FIRST_CONTACT_DATE TIMESTAMP WITH TIME ZONE,
    LAST_CONTACT_DATE TIMESTAMP WITH TIME ZONE,
    EPICCARE_PAT_YN VARCHAR(100),
    MEDICARE_NUM VARCHAR(100),
    MEDICAID_NUM VARCHAR(100),
    ADV_DIRECTIVE_YN VARCHAR(100),
    INTRPTR_NEEDED_YN VARCHAR(100),
    TXP_PAT_YN VARCHAR(100),
    ALRGY_REV_EPT_CSN INTEGER,
    MEDS_LAST_REV_CSN INTEGER,
    ALLERGY_REVIEW_STATUS VARCHAR(100),
    CUR_PCP_PROV_ID VARCHAR(100),
    CUR_PRIM_LOC_ID INTEGER,
    PRIM_CVG_ID INTEGER,
    PRIM_EPM_ID VARCHAR(100),
    PRIM_EPP_ID BIGINT,
    ALRGY_UPD_USER_ID VARCHAR(100),
    MEDS_LST_REV_USR_ID VARCHAR(100),
    FIRST_APPT_DEPT_ID INTEGER,
    hx_pat_enc_csn_id INTEGER,
    MGI_YN VARCHAR(100),
    MGI_DATE TIMESTAMP WITH TIME ZONE,
    ADI_NATRANK INTEGER,
    RUCA VARCHAR(100),
    PPV_YN VARCHAR(100),
    DVS_YN VARCHAR(100),
    DCI_Distress_Score NUMERIC(18,6)

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologySurgeryDm (
    OR_CAT VARCHAR(100),
    OR_CAT_ID VARCHAR(100),
    OR_PROC_ID VARCHAR(100),
    OR_PROC_NAME VARCHAR(100)

    --table_constraints
    );

CREATE TABLE IF NOT EXISTS ehr.OphthalmologyEncounterDiagnoses (
    PAT_ENC_CSN_ID INTEGER,
    PAT_MRN VARCHAR(100),
    PAT_ID VARCHAR(100),
    CONTACT_DATE TIMESTAMP WITH TIME ZONE,
    LINE INTEGER,
    DX_ID INTEGER,
    DX_NAME VARCHAR(500),
    PRIMARY_DX_YN VARCHAR(100),
    ANNOTATION INTEGER,
    COMMENTS INTEGER,
    DX_LINK_PROB_ID INTEGER

    --table_constraints
    );

