DROP TABLE IF EXISTS coris_registry.C3304_GBQ_T15_Referral_20240207;
CREATE TABLE coris_registry.C3304_GBQ_T15_Referral_20240207
(
  Arb_Person_ID INTEGER,
  Arb_Encounter_Id INTEGER,
  ReferralEpicId INTEGER,
  CreationInstant TIMESTAMP WITH TIME ZONE,
  ReferringProv VARCHAR,
  ReferringDep VARCHAR,
  ReferredToProv VARCHAR,
  ReferredToDep VARCHAR,
  FirstReasonForReferral VARCHAR,
  SecondReasonForReferral VARCHAR,
  ThirdReasonForReferral VARCHAR
);

DROP TABLE IF EXISTS coris_registry.C3304_GBQ_T4_Proc_OrderedEMR_20240207;
CREATE TABLE coris_registry.C3304_GBQ_T4_Proc_OrderedEMR_20240207
(
  Arb_Person_Id INTEGER,
  Arb_Encounter_Id INTEGER,
  Arb_Procedure_ID INTEGER,
  ProcedureEpicId INTEGER,
  ProcedureName VARCHAR,
  PatientFriendlyName VARCHAR,
  ProcedureCode VARCHAR,
  ProcedureDate TIMESTAMP WITHOUT TIME ZONE,
  ProcedureTime TIME WITHOUT TIME ZONE,
  ProviderRole VARCHAR,
  Department VARCHAR,
  PerformingProvName VARCHAR,
  AppointmentStatus VARCHAR,
  PrimaryLocation VARCHAR
);

DROP TABLE IF EXISTS coris_registry.C3304_T1_Person_20231222;
CREATE TABLE coris_registry.C3304_T1_Person_20231222
(
  Arb_Person_Id INTEGER,
  PrimaryMrn VARCHAR,
  BirthDate TIMESTAMP WITHOUT TIME ZONE,
  Name VARCHAR,
  Sex VARCHAR,
  Race VARCHAR,
  Ethnicity VARCHAR,
  PrimaryLanguage VARCHAR,
  NeedInterpreter VARCHAR,
  PayorFinancialClass VARCHAR,
  ZipCode VARCHAR,
  DeceasedYN VARCHAR,
  CDPHE_DOD TIMESTAMP WITHOUT TIME ZONE,
  DateOfDeathEMR TIMESTAMP WITHOUT TIME ZONE,
  CauseOfDeath VARCHAR
);

DROP TABLE IF EXISTS coris_registry.C3304_GBQ_T6_Surgeries_20240207;
CREATE TABLE coris_registry.C3304_GBQ_T6_Surgeries_20240207
(
  Arb_Person_ID INTEGER,
  Arb_Encounter_Id INTEGER,
  SurgicalCaseEpicId VARCHAR,
  SurgeryProcedureID VARCHAR,
  ProcedureName VARCHAR,
  PatientFriendlyName VARCHAR,
  DisplayName VARCHAR,
  DateOfProcedure TIMESTAMP WITHOUT TIME ZONE,
  TimeOfProcedure TIME WITHOUT TIME ZONE,
  DepartmentName VARCHAR,
  TeamType VARCHAR,
  LogStatus VARCHAR,
  PrimaryProviderName VARCHAR,
  PrimaryProviderType VARCHAR,
  SecondProvName VARCHAR,
  SecondProvType VARCHAR,
  ThirdProvName VARCHAR,
  ThirdProvType VARCHAR
);

DROP TABLE IF EXISTS coris_registry.C3304_T11_Notes_20231222;
CREATE TABLE coris_registry.C3304_T11_Notes_20231222
(
  Arb_Person_Id INTEGER,
  Arb_Encounter_Id INTEGER,
  NoteEpicId VARCHAR,
  NoteType VARCHAR,
  NoteText VARCHAR,
  NoteProvider VARCHAR,
  DateOfNote TIMESTAMP WITHOUT TIME ZONE,
  TimeOfNote TIME WITHOUT TIME ZONE
);

DROP TABLE IF EXISTS coris_registry.C3304_GBQ_T16_CensusData2018_20240207;
CREATE TABLE coris_registry.C3304_GBQ_T16_CensusData2018_20240207
(
  arb_person_id INTEGER,
  EP_POV_18 NUMERIC,
  EP_UNEMP_18 NUMERIC,
  EP_PCI_18 NUMERIC,
  EP_NOHSDP_18 NUMERIC,
  EP_AGE65_18 NUMERIC,
  EP_AGE17_18 NUMERIC,
  EP_DISABL_18 NUMERIC,
  EP_SNGPNT_18 NUMERIC,
  EP_MINRTY_18 NUMERIC,
  EP_LIMENG_18 NUMERIC,
  EP_MUNIT_18 NUMERIC,
  EP_MOBILE_18 NUMERIC,
  EP_CROWD_18 NUMERIC,
  EP_NOVEH_18 NUMERIC,
  EP_GROUPQ_18 NUMERIC,
  EPL_POV_18 NUMERIC,
  EPL_UNEMP_18 NUMERIC,
  EPL_PCI_18 NUMERIC,
  EPL_NOHSDP_18 NUMERIC,
  SPL_THEME1_18 NUMERIC,
  RPL_THEME1_18 NUMERIC,
  EPL_AGE65_18 NUMERIC,
  EPL_AGE17_18 NUMERIC,
  EPL_DISABL_18 NUMERIC,
  EPL_SNGPNT_18 NUMERIC,
  SPL_THEME2_18 NUMERIC,
  RPL_THEME2_18 NUMERIC,
  EPL_MINRTY_18 NUMERIC,
  EPL_LIMENG_18 NUMERIC,
  SPL_THEME3_18 NUMERIC,
  RPL_THEME3_18 NUMERIC,
  EPL_MUNIT_18 NUMERIC,
  EPL_MOBILE_18 NUMERIC,
  EPL_CROWD_18 NUMERIC,
  EPL_NOVEH_18 NUMERIC,
  EPL_GROUPQ_18 NUMERIC,
  SPL_THEME4_18 NUMERIC,
  RPL_THEME4_18 NUMERIC,
  SPL_THEMES_18 NUMERIC,
  RPL_THEMES_18 NUMERIC,
  F_POV_18 NUMERIC,
  F_UNEMP_18 NUMERIC,
  F_PCI_18 NUMERIC,
  F_NOHSDP_18 NUMERIC,
  F_THEME1_18 NUMERIC,
  F_AGE65_18 NUMERIC,
  F_AGE17_18 NUMERIC,
  F_DISABL_18 NUMERIC,
  F_SNGPNT_18 NUMERIC,
  F_THEME2_18 NUMERIC,
  F_MINRTY_18 NUMERIC,
  F_LIMENG_18 NUMERIC,
  F_THEME3_18 NUMERIC,
  F_MUNIT_18 NUMERIC,
  F_MOBILE_18 NUMERIC,
  F_CROWD_18 NUMERIC,
  F_NOVEH_18 NUMERIC,
  F_GROUPQ_18 NUMERIC,
  F_THEME4_18 NUMERIC,
  F_TOTAL_18 NUMERIC,
  PctNoInternet_18 NUMERIC,
  PctBroadband_18 NUMERIC,
  PctNoComputer_18 NUMERIC,
  Pct_forborn_18 NUMERIC,
  PctNoHealthIns_18 NUMERIC,
  PctNoHealthIns_19to64_18 NUMERIC,
  NCHS_urban_18 NUMERIC
);

DROP TABLE IF EXISTS coris_registry.C3304_GBQ_T11_Notes_20240207;
CREATE TABLE coris_registry.C3304_GBQ_T11_Notes_20240207
(
  Arb_Person_Id INTEGER,
  Arb_Encounter_Id INTEGER,
  NoteEpicId VARCHAR,
  NoteType VARCHAR,
  NoteText VARCHAR,
  NoteProvider VARCHAR,
  DateOfNote TIMESTAMP WITHOUT TIME ZONE,
  TimeOfNote TIME WITHOUT TIME ZONE
);

DROP TABLE IF EXISTS coris_registry.C3304_GBQ_T5_Procedures_20240207;
CREATE TABLE coris_registry.C3304_GBQ_T5_Procedures_20240207
(
  Arb_Person_Id INTEGER,
  Arb_Encounter_Id INTEGER,
  Arb_Procedure_ID INTEGER,
  ProcedureEpicId INTEGER,
  ProcedureName VARCHAR,
  PatientFriendlyName VARCHAR,
  ProcedureCode VARCHAR,
  ProcedureDate TIMESTAMP WITHOUT TIME ZONE,
  ProcedureTime TIME WITHOUT TIME ZONE,
  ProviderRole VARCHAR,
  Department VARCHAR,
  PerformingProvName VARCHAR,
  PrimaryLocation VARCHAR
);

DROP TABLE IF EXISTS coris_registry.C3304_GBQ_T8_Labs_20240207;
CREATE TABLE coris_registry.C3304_GBQ_T8_Labs_20240207
(
  Arb_Person_ID INTEGER,
  Arb_Encounter_Id INTEGER,
  LabEpicID VARCHAR,
  LabOrderEpicId INTEGER,
  LabName VARCHAR,
  PanelName VARCHAR,
  ComponentName VARCHAR,
  NumericValue NUMERIC,
  Unit VARCHAR,
  ReferenceRange VARCHAR,
  CollectionDate TIMESTAMP WITHOUT TIME ZONE,
  ResultDate TIMESTAMP WITHOUT TIME ZONE,
  AuthorizingProv VARCHAR,
  OrderingProv VARCHAR,
  LoincCode VARCHAR
);

DROP TABLE IF EXISTS coris_registry.C3304_GBQ_T2_Encounter_20240207;
CREATE TABLE coris_registry.C3304_GBQ_T2_Encounter_20240207
(
  Arb_Person_ID INTEGER,
  Arb_Encounter_Id INTEGER,
  Department VARCHAR,
  DepartmentSpecialty VARCHAR,
  EncounterType VARCHAR,
  PatientClass VARCHAR,
  date TIMESTAMP WITH TIME ZONE,
  AdmissionDate TIMESTAMP WITHOUT TIME ZONE,
  DischargeDate TIMESTAMP WITHOUT TIME ZONE,
  LOSDays INTEGER,
  LOSHours INTEGER,
  ICULOSDays INTEGER,
  ProviderName VARCHAR,
  PrimarySpecialty VARCHAR,
  PayorFinancialClass VARCHAR,
  PayorName VARCHAR
);

DROP TABLE IF EXISTS coris_registry.C3304_GBQ_T1_Person_20240207;
CREATE TABLE coris_registry.C3304_GBQ_T1_Person_20240207
(
  Arb_Person_Id INTEGER,
  PrimaryMrn VARCHAR,
  BirthDate TIMESTAMP WITHOUT TIME ZONE,
  Name VARCHAR,
  Sex VARCHAR,
  Race VARCHAR,
  Ethnicity VARCHAR,
  PrimaryLanguage VARCHAR,
  NeedInterpreter VARCHAR,
  PayorFinancialClass VARCHAR,
  ZipCode VARCHAR,
  DeceasedYN VARCHAR,
  CDPHE_DOD TIMESTAMP WITHOUT TIME ZONE,
  DateOfDeathEMR TIMESTAMP WITHOUT TIME ZONE,
  CauseOfDeath VARCHAR
);

DROP TABLE IF EXISTS coris_registry.C3304_GBQ_T14_Allergy_20240207;
CREATE TABLE coris_registry.C3304_GBQ_T14_Allergy_20240207
(
  Arb_Person_ID INTEGER,
  AllergenEpicId INTEGER,
  AllergyName VARCHAR,
  AllergyReactions VARCHAR,
  AllergyStartDate TIMESTAMP WITHOUT TIME ZONE,
  AllergyEndDate TIMESTAMP WITHOUT TIME ZONE
);

DROP TABLE IF EXISTS coris_registry.C3304_GBQ_T18_OphthamologyExams_20240207;
CREATE TABLE coris_registry.C3304_GBQ_T18_OphthamologyExams_20240207
(
  Arb_Person_ID INTEGER,
  Arb_Encounter_Id INTEGER,
  SmartDataElementEpicId VARCHAR,
  ExamName VARCHAR,
  Abbreviation VARCHAR,
  Value VARCHAR,
  Date TIMESTAMP WITHOUT TIME ZONE
);

DROP TABLE IF EXISTS coris_registry.C3304_GBQ_T9_ADT_20240207;
CREATE TABLE coris_registry.C3304_GBQ_T9_ADT_20240207
(
  Arb_Patient_Id INTEGER,
  Arb_Encounter_Id INTEGER,
  DepartmentEpicId VARCHAR,
  HospitalUnit VARCHAR,
  line_number INTEGER,
  PatientClass VARCHAR,
  EventType VARCHAR,
  AdmissionType VARCHAR,
  DischargeDisposition VARCHAR,
  TransferInDate TIMESTAMP WITHOUT TIME ZONE,
  TransferOutTime TIME WITHOUT TIME ZONE,
  TimeValue TIME WITHOUT TIME ZONE
);

DROP TABLE IF EXISTS coris_registry.C3304_GBQ_T13_SocialHistory_20240207;
CREATE TABLE coris_registry.C3304_GBQ_T13_SocialHistory_20240207
(
  Arb_Person_Id INTEGER,
  Arb_Encounter_Id INTEGER,
  Date TIMESTAMP WITHOUT TIME ZONE,
  CigarettePacksPerDay NUMERIC,
  TobaccoUseInYears NUMERIC,
  AlcoholOzPerWeek VARCHAR,
  IllicitDrugFreqPerWeek NUMERIC,
  Cigarettes INTEGER,
  Pipes INTEGER,
  Cigars INTEGER,
  Snuff INTEGER,
  Chew INTEGER,
  IVDrugUser INTEGER,
  TobaccoUse VARCHAR,
  TobaccoUseComment VARCHAR,
  SmokingTobaccoUse VARCHAR,
  SmokelessTobaccoUse VARCHAR,
  SmokelessTobaccoQuitDate TIMESTAMP WITHOUT TIME ZONE,
  AlcoholUseComment VARCHAR,
  AlcoholUse VARCHAR,
  IllicitDrugUseComment VARCHAR,
  IllicitDrugUse VARCHAR
);

DROP TABLE IF EXISTS coris_registry.C3304_GBQ_T3_Diagnosis_20240207;
CREATE TABLE coris_registry.C3304_GBQ_T3_Diagnosis_20240207
(
  Arb_Person_ID INTEGER,
  Arb_Encounter_Id INTEGER,
  DiagnosisCodeType VARCHAR,
  DiagnosisCode VARCHAR,
  DiagnosisDescription VARCHAR,
  EncounterDate TIMESTAMP WITHOUT TIME ZONE,
  ProblemOnsetDate TIMESTAMP WITHOUT TIME ZONE,
  ProblemResolutonDate TIMESTAMP WITHOUT TIME ZONE,
  Provenance VARCHAR
);

DROP TABLE IF EXISTS coris_registry.C3304_T3_Diagnosis_20231222;
CREATE TABLE coris_registry.C3304_T3_Diagnosis_20231222
(
  Arb_Person_ID INTEGER,
  Arb_Encounter_Id INTEGER,
  DiagnosisCodeType VARCHAR,
  DiagnosisCode VARCHAR,
  DiagnosisDescription VARCHAR,
  EncounterDate TIMESTAMP WITHOUT TIME ZONE,
  ProblemOnsetDate TIMESTAMP WITHOUT TIME ZONE,
  ProblemResolutonDate TIMESTAMP WITHOUT TIME ZONE,
  Provenance VARCHAR
);

DROP TABLE IF EXISTS coris_registry.C3304_GBQ_T17_CensusData2014_20240207;
CREATE TABLE coris_registry.C3304_GBQ_T17_CensusData2014_20240207
(
  arb_person_id INTEGER,
  EP_POV_14 NUMERIC,
  EP_UNEMP_14 NUMERIC,
  EP_PCI_14 NUMERIC,
  EP_NOHSDP_14 NUMERIC,
  EP_AGE65_14 NUMERIC,
  EP_AGE17_14 NUMERIC,
  EP_DISABL_14 NUMERIC,
  EP_SNGPNT_14 NUMERIC,
  EP_MINRTY_14 NUMERIC,
  EP_LIMENG_14 NUMERIC,
  EP_MUNIT_14 NUMERIC,
  EP_MOBILE_14 NUMERIC,
  EP_CROWD_14 NUMERIC,
  EP_NOVEH_14 NUMERIC,
  EP_GROUPQ_14 NUMERIC,
  EPL_POV_14 NUMERIC,
  EPL_UNEMP_14 NUMERIC,
  EPL_PCI_14 NUMERIC,
  EPL_NOHSDP_14 NUMERIC,
  SPL_THEME1_14 NUMERIC,
  RPL_THEME1_14 NUMERIC,
  EPL_AGE65_14 NUMERIC,
  EPL_AGE17_14 NUMERIC,
  EPL_DISABL_14 NUMERIC,
  EPL_SNGPNT_14 NUMERIC,
  SPL_THEME2_14 NUMERIC,
  RPL_THEME2_14 NUMERIC,
  EPL_MINRTY_14 NUMERIC,
  EPL_LIMENG_14 NUMERIC,
  SPL_THEME3_14 NUMERIC,
  RPL_THEME3_14 NUMERIC,
  EPL_MUNIT_14 NUMERIC,
  EPL_MOBILE_14 NUMERIC,
  EPL_CROWD_14 NUMERIC,
  EPL_NOVEH_14 NUMERIC,
  EPL_GROUPQ_14 NUMERIC,
  SPL_THEME4_14 NUMERIC,
  RPL_THEME4_14 NUMERIC,
  SPL_THEMES_14 NUMERIC,
  RPL_THEMES_14 NUMERIC,
  F_POV_14 NUMERIC,
  F_UNEMP_14 NUMERIC,
  F_PCI_14 NUMERIC,
  F_NOHSDP_14 NUMERIC,
  F_THEME1_14 NUMERIC,
  F_AGE65_14 NUMERIC,
  F_AGE17_14 NUMERIC,
  F_DISABL_14 NUMERIC,
  F_SNGPNT_14 NUMERIC,
  F_THEME2_14 NUMERIC,
  F_MINRTY_14 NUMERIC,
  F_LIMENG_14 NUMERIC,
  F_THEME3_14 NUMERIC,
  F_MUNIT_14 NUMERIC,
  F_MOBILE_14 NUMERIC,
  F_CROWD_14 NUMERIC,
  F_NOVEH_14 NUMERIC,
  F_GROUPQ_14 NUMERIC,
  F_THEME4_14 NUMERIC,
  F_TOTAL_14 NUMERIC,
  Pct_forborn_14 NUMERIC,
  PctNoHealthIns_14 NUMERIC,
  PctNoHealthIns_18to64_14 NUMERIC,
  NCHS_urban_14 NUMERIC
);

DROP TABLE IF EXISTS coris_registry.C3304_GBQ_T10_Flowsheets_20240207;
CREATE TABLE coris_registry.C3304_GBQ_T10_Flowsheets_20240207
(
  Arb_Person_Id INTEGER,
  Arb_Encounter_Id INTEGER,
  FlowsheetTemplateEpicId VARCHAR,
  FlowsheetRowEpicId VARCHAR,
  FlowsheetTemplateName VARCHAR,
  FlowsheetRowName VARCHAR,
  DisplayName VARCHAR,
  Value VARCHAR,
  NumericValue NUMERIC,
  Unit VARCHAR,
  FlowsheetDate TIMESTAMP WITH TIME ZONE,
  TakenByEmployee VARCHAR,
  DocumentedByEmployee VARCHAR
);

DROP TABLE IF EXISTS coris_registry.C3304_T18_OphthamologyExams_20231222;
CREATE TABLE coris_registry.C3304_T18_OphthamologyExams_20231222
(
  Arb_Person_ID INTEGER,
  Arb_Encounter_Id INTEGER,
  SmartDataElementEpicId VARCHAR,
  ExamName VARCHAR,
  Abbreviation VARCHAR,
  Value VARCHAR,
  Date TIMESTAMP WITHOUT TIME ZONE
);

DROP TABLE IF EXISTS coris_registry.C3304_GBQ_T12_FamilyHistory_20240207;
CREATE TABLE coris_registry.C3304_GBQ_T12_FamilyHistory_20240207
(
  Arb_Person_ID INTEGER,
  RelationEpicId VARCHAR,
  ProblemEpicId INTEGER,
  FamilyRelation VARCHAR,
  MedicalProblem VARCHAR,
  EffectiveDate VARCHAR
);

DROP TABLE IF EXISTS coris_registry.C3304_T2_Encounter_20231222;
CREATE TABLE coris_registry.C3304_T2_Encounter_20231222
(
  Arb_Person_ID INTEGER,
  Arb_Encounter_Id INTEGER,
  Department VARCHAR,
  DepartmentSpecialty VARCHAR,
  EncounterType VARCHAR,
  PatientClass VARCHAR,
  date TIMESTAMP WITH TIME ZONE,
  AdmissionDate TIMESTAMP WITHOUT TIME ZONE,
  DischargeDate TIMESTAMP WITHOUT TIME ZONE,
  LOSDays INTEGER,
  LOSHours INTEGER,
  ICULOSDays INTEGER,
  ProviderName VARCHAR,
  PrimarySpecialty VARCHAR,
  PayorFinancialClass VARCHAR,
  PayorName VARCHAR
);

